version: '3.8'

services:
  jira-logger:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jira-logger
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./jira_logger/data:/app/jira_logger/data
      - ./.env:/app/.env
    environment:
      - TZ=UTC
      - USE_SSL_VERIFICATION=false
    command: python jira_logger/run_api.py
    networks:
      - jira-logger-network

  jira-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jira-scheduler
    restart: unless-stopped
    volumes:
      - ./jira_logger/data:/app/jira_logger/data
      - ./.env:/app/.env
    environment:
      - TZ=UTC
      - USE_SSL_VERIFICATION=false
    command: python jira_logger/main.py
    networks:
      - jira-logger-network

networks:
  jira-logger-network:
    driver: bridge
