name: Deploy to Cloud Run

on:
  push:
    branches:
    - main # or your default branch name
  workflow_dispatch:
    # Allows manual triggering

env:
  PROJECT_ID: tp-pmo-production # Google Cloud Project ID
  REGION: europe-west3 # Google Cloud Region - Frankfurt
  SERVICE_NAME: jira-logger # TODO: Replace with your service name

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug Workload Identity Provider
      run: |
        echo "WIF_PROVIDER: ${{ secrets.WIF_PROVIDER }}"
        echo "PROJECT_ID: ${{ env.PROJECT_ID }}"

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: projects/924413780529/locations/global/workloadIdentityPools/github-pool/providers/git
        service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
        project_id: ${{ env.PROJECT_ID }}
        audience: api://924413780529.apps.googleusercontent.com

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Build and Push Container
      run: |-
        docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}
