name: Deploy to Cloud Run

on:
  push:
    branches:
    - main # or your default branch name
  workflow_dispatch:
    # Allows manual triggering

env:
  PROJECT_ID: tp-pmo-production # Google Cloud Project ID
  REGION: europe-west3 # Google Cloud Region - Frankfurt
  SERVICE_NAME: jira-logger # TODO: Replace with your service name

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: https://iam.googleapis.com/projects/924413780529/locations/global/workloadIdentityPools/github-pool/providers/git
        service_account: github-actions-sa@tp-pmo-production.iam.gserviceaccount.com
        token_format: 'access_token'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Build and Push Container
      run: |-
        docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: ${{ env.SERVICE_NAME }}
        region: ${{ env.REGION }}
        image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}
